export const typeColors = {
  normal:   { bg: 'bg-gray-200',    text: 'text-gray-800' },
  fire:     { bg: 'bg-red-200',     text: 'text-red-800' },
  water:    { bg: 'bg-blue-200',    text: 'text-blue-800' },
  electric: { bg: 'bg-yellow-200',  text: 'text-yellow-800' },
  grass:    { bg: 'bg-green-200',   text: 'text-green-800' },
  ice:      { bg: 'bg-cyan-200',    text: 'text-cyan-800' },
  fighting: { bg: 'bg-orange-200',  text: 'text-orange-800' },
  poison:   { bg: 'bg-purple-200',  text: 'text-purple-800' },
  ground:   { bg: 'bg-yellow-300',  text: 'text-yellow-900' },
  flying:   { bg: 'bg-indigo-200',  text: 'text-indigo-800' },
  psychic:  { bg: 'bg-pink-200',    text: 'text-pink-800' },
  bug:      { bg: 'bg-lime-200',    text: 'text-lime-800' },
  rock:     { bg: 'bg-yellow-400',  text: 'text-yellow-900' },
  ghost:    { bg: 'bg-indigo-300',  text: 'text-indigo-900' },
  dragon:   { bg: 'bg-purple-300',  text: 'text-purple-900' },
  dark:     { bg: 'bg-gray-700',    text: 'text-gray-100' },
  steel:    { bg: 'bg-gray-400',    text: 'text-gray-900' },
  fairy:    { bg: 'bg-pink-100',    text: 'text-pink-700' },
};
